#!/bin/sh
echo "================================="
echo " i.MX6ULL JJL Linux Boot"
echo "================================="
mount -t proc proc /proc
mount -t sysfs sysfs /sys
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
